### ISSUE TITLE
suddenly stopped working?

### ISSUE THREAD

**Issue by JRHB314** [AlexWaveDiver/TranslaTale#3]
I have Windows 10, and I just downloaded the exe. It was working okay, at least it seemed to be, until I loaded the game. The changes did not show up. It apears to just be dumping the files into the folder where I have TranslaTale instead of actually repacking them?
Trying to see whether the files were changed in the data.win file, I tried dumping images again. The program runs, but when I look in the destination folder nothing is there.

**Comment by JRHB314** [comment]
also it's not the data.win file itself, as I was using another extractor before (it just didn't have a reimport option), and double-checking with that all of the data is still there

**Comment by JRHB314** [comment]
update: after reloading transalatale it's extracting again but it is still not modifying the data.win file when I attempt to repack.

**Comment by JRHB314** [comment]
it apears to just be dumping the files into the folder where I have TranslaTale instead of actually repacking them?

**Comment by fjay69** [comment]
Hello! My tools are still working. Help me to improve them!

**Comment by JRHB314** [comment]
well fjay69 I tried it out but I can't seem to run it. I can't even figure out what file to open.

**Comment by MateusinhoEX** [comment]
Hey, don't worry, the problem is not with Translatale itself, I think. Tell me, are you using the new updated version of Undertale? Most tools, like the GMKTool included in Translatale, are not being able to unpack and repack the files from the new "data.win". I am part of a tam translating the game, too, and the only tool that is still working fine for unpackign and repacking seems to be the tools for adding fonts created by fjay69. Adding fonts, though, edit the data file in a way it can't be repacked again afterwards, so we are creating a backup before editing data.win for testing, then restoring it afterwards.

**Comment by JRHB314** [comment]
Yes, I have been using the new updated version. Didn't think to make a backup. Is the problem fixable? That is, should I be looking forward to a new working version of TranslaTale (or some other tool), or should I try to get a pre-patch version of Undertale?

**Comment by AlexWaveDiver** [comment]
I'm about to release a new version on the next few days, compatible with the new v1.001 (using fjay69's toolset)

**Comment by JRHB314** [comment]
any updates?

**Comment by AlexWaveDiver** [comment]
Still on it.

**Comment by AlexWaveDiver** [comment]
Ok, the new release is ready. It should work now!
